version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-free
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: